#!/usr/bin/env bash
# displays information about subdomains


describe()
{
    if [ $# -eq 2 ]; then
        dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{split($1, spl, ".")} {printf "The subdomain %s is a %s record and points to %s\n",spl[1],$4,$5}'
    elif [ $# -eq 1 ]; then
        for sub in 'www' 'lb-01' 'web-01' 'web-02'; do
            url=$sub.$1
            dig "$url" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{split($1, spl, ".")} {printf "The subdomain %s is a %s record and points to %s\n",spl[1],$4,$5}'
        done
    fi
}

describe "$@"
