#!/usr/bin/env bash
# installs ngiz on my web-01

WHERE="/etc/nginx/sites-available/default"
ADD="\\\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=xzOIj4_QBE0;\n\t}\n"
sudo apt update
sudo apt install -y nginx-full
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "30i $ADD" $WHERE
sudo service nginx restart
