#!/usr/bin/env bash
# configure load balance
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt-get update
sudo apt-get install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "frontend haproxy-main
		bind *:80
    	option forwardfor  
    	default_backend apache_webservers    

backend apache_webservers
    	balance roundrobin
    	server 82829-web-01	100.26.161.5:80 check
    	server 82829-web-02	3.85.148.233:80 check"
sudo systemctl restart haproxy
