#!/usr/bin/env bash
# install load balancer with round robin
apt-get update
apt-get install -y software-properties-common
yes enter | add-apt-repository ppa:vbernat/haproxy-2.6 -y
apt-get update && apt-get upgrade -y
apt-get install -y haproxy=2.6.\*
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
echo -e "\nfrontend 82829-lb-01\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 82829-web-01 100.26.161.5:80 check\n\tserver 82829-web-02 3.85.148.233:80 check" >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
