#!/usr/bin/env bash
# run nginx as nginx user listening on port 8080
pkill apache2
sed -i "s/#user www-data/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart

